### PR TITLE
Implementing GraphQL structure

### PR DESCRIPTION
**Pull request by soundstep**
The current CLI:
```
postman2openapi v1.0.0-dev.+
commit:
date: 2022-08-01T12:05:58Z
```
is having issues with GraphQL collections:
https://github.com/kevinswiber/postman2openapi/issues/41

### CODE REVIEW

**Comment by soundstep** [comment]
Getting closer, but I'm new to Rust.

I'm attempting to transform the postman graphql object to a json body with a `query` property containing the query.

Any idea how I can change what I currently have:
```
      requestBody:
        content:
          application/json:
            example: |
              {
```

To:
```
      requestBody:
        content:
          application/json:
            example:
              query: |-
                {
```

I think I just need to add a root property of `query` and wrap what I already have, I can't seem to find a way to do that with `serde_json`, any clue?

**Comment by kevinswiber** [comment]
Hey @soundstep, thanks for this!

I made some changes here.  The request body schema is going to be the same for all GraphQL requests, so I hardcoded it.  I included some code to generate the examples, as well.  Take a look below.  What do you think?

> **Note**
> Can you allow me to push to this branch so we can collaborate?  See here: [Allowing changes to a pull request branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
> 
> Otherwise, you can save the following patch file as something like `graphql-collection.patch` and apply it locally using `git am graphql-collection.patch`.

```patch
From 235b079dbdd61dd063363d81d6d1cfccdef2c49a Mon Sep 17 00:00:00 2001
From: Kevin Swiber <kswiber@gmail.com>
Date: Mon, 1 Aug 2022 16:11:08 -0700
Subject: [PATCH] Adding support for examples on GraphQL requests.

---
 src/lib.rs | 35 ++++++++++++++++++++++++++++++++---
 1 file changed, 32 insertions(+), 3 deletions(-)

diff --git a/src/lib.rs b/src/lib.rs
index ebae0b3..4da5225 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -270,7 +270,6 @@ impl<'a> Transpiler<'a> {
             })
             .collect::<Vec<String>>();
         let segments = "/".to_string() + &resolved_segments.join("/");
-
         // TODO: Because of variables, we can actually get duplicate paths.
         // - /admin/{subresource}/{subresourceId}
         // - /admin/{subresource2}/{subresource2Id}
@@ -636,11 +635,41 @@ impl<'a> Transpiler<'a> {
 
                 postman::Mode::GraphQl => {
                     content_type = Some("application/json".to_string());
+
+                    // The schema is the same for every GraphQL request.
+                    content.schema = Some(ObjectOrReference::Object(openapi3::Schema {
+                        schema_type: Some("object".to_owned()),
+                        properties: Some(BTreeMap::from([
+                            (
+                                "query".to_owned(),
+                                openapi3::Schema {
+                                    schema_type: Some("string".to_owned()),
+                                    ..openapi3::Schema::default()
+                                },
+                            ),
+                            (
+                                "variables".to_owned(),
+                                openapi3::Schema {
+                                    schema_type: Some("object".to_owned()),
+                                    ..openapi3::Schema::default()
+                                },
+                            ),
+                        ])),
+                        ..openapi3::Schema::default()
+                    }));
+
                     if let Some(postman::GraphQlBody::GraphQlBodyClass(graphql)) = &body.graphql {
                         if let Some(query) = &graphql.query {
-                            let example_val = serde_json::Value::String(query.to_string());
+                            let mut example_map = serde_json::Map::new();
+                            example_map.insert("query".to_owned(), query.to_owned().into());
+                            if let Some(vars) = &graphql.variables {
+                                if let Ok(vars) = serde_json::from_str::<serde_json::Value>(vars) {
+                                    example_map.insert("variables".to_owned(), vars);
+                                }
+                            }
+
                             let example = openapi3::MediaTypeExample::Example {
-                                example: example_val,
+                                example: serde_json::Value::Object(example_map),
                             };
                             content.examples = Some(example);
                         }
-- 
2.31.0

```

**Comment by soundstep** [comment]
@kevinswiber Thanks for that!

Please ignore some commits (we can merge-squash), I was trying to find ways to write that in Rust but your patch looks great! I've applied it. "Allow edits by maintainers" was already ticked, I think you can push? (I'll add you as a user in my fork just in case).

I got it working with a collection containing a single graphql request, but with a collection containing 3 mixed requests, the graphql is missing I think.

Using this collection: https://gist.github.com/soundstep/aba44f8b453e28418814122209c176db

I see `GET discovery PRD`, `POST discovery PRD raw` but I seem to be missing the `POST discovery PRD` (the graphql one). Can you confirm that's the case and I'm executing that correctly?

I debug the binary with a vscode launch file and then run:
```
./target/debug/postman2openapi my-collection.json > test.yml
```

**Comment by kevinswiber** [comment]
> I see `GET discovery PRD`, `POST discovery PRD raw` but I seem to be missing the `POST discovery PRD` (the graphql one). Can you confirm that's the case and I'm executing that correctly?

The operations are stomping on each other.  Both use `POST` and `/discovery`.  There isn't automatic merging of operations at this time, as it can get quite complex, though it is something I'm looking at in the future.  Change the collection to use a different path or put the `graphql` one last, and you should see it in the results.

**Comment by kevinswiber** [comment]
Thanks, @soundstep!  This has been merged into main.  I added a unit test.  Appreciate it!  🎉

**Comment by soundstep** [comment]
@kevinswiber you did it all! Thanks for getting that in!

**Pull request merged**
